# Use the acc-py-gitlab templates found at
# https://gitlab.cern.ch/acc-co/devops/python/acc-py-gitlab-ci-templates/-/blob/master/v2/python.gitlab-ci.yml.
stages:
  - build
  - test
  - publish

include:
  - project: acc-co/devops/python/acc-py-gitlab-ci-templates
    file: v2/python.gitlab-ci.yml

variables:
  project_name: simple_repository
  project_root: .


pre-commit:
  extends: .acc_py_pre-commit


build_wheel:
  extends: .acc_py_build_wheel


# A full installation of simple-repository, tested with pytest.
wheel_test:
  extends:
    - .acc_py_wheel_test
    - .acc_py_run_on_all_currently_supported


# A development installation of simple-repository, tested with pytest.
test_dev:
  extends:
    - .acc_py_dev_test
    - .acc_py_run_on_all_currently_supported


static_analysis_wheel:
  extends:
    - .acc_py_wheel_test
    - .acc_py_run_on_all_currently_supported
  before_script:
    - !reference [.acc_py_wheel_test, before_script]
    - python -m pip install $(ls -A ${project_root}/wheel-to-install/*.whl)[dev] mypy
  script:
    - python -m mypy -p simple_repository


publish_package_to_index:
  stage: publish
  extends: .acc_py_publish
