repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/asottile/add-trailing-comma
    rev: "v2.1.0"
    hooks:
      - id: add-trailing-comma
        args: [ "--py36-plus" ]

  - repo: https://github.com/PyCQA/isort
    rev: "5.9.3"
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
        args:
          - "--max-line-length=100"
          - "--per-file-ignores=pyda/tests/*.py:E501"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.942"
    hooks:
      - id: mypy

  - repo: https://github.com/hadolint/hadolint
    rev: "v2.10.0"
    hooks:
      - id: hadolint

  - repo: https://gitlab.com/devopshq/gitlab-ci-linter
    rev: v1.0.2
    hooks:
      - id: gitlab-ci-linter
        files: '.gitlab-ci.yml'
        args: [ "--server", "https://gitlab.cern.ch" ]
